
import java.awt.Font;
import javax.swing.JOptionPane;
import java.lang.String;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sandi
 */
public class SimplexUI extends javax.swing.JFrame {
    
    private int cantRestr;
    private float valorFinalZ, 
                    valorFinalX, 
                    valorFinalY,
                    valorInputX,
                    valorInputY;

    /**
     * Creates new form UIFrame
     */
    public SimplexUI() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputX = new keeptoo.KButton();
        CerrarBoton = new keeptoo.KButton();
        inputRestr = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputY = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        ValorZPanel = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        ValorXPanel = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        ValorYPanel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        noResText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRestricciones = new javax.swing.JTable();
        CalcularBoton = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 720));

        inputX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_add_32.png"))); // NOI18N
        inputX.setText("Ingresar Valor X");
        inputX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputX.setkAllowGradient(false);
        inputX.setkBackGroundColor(new java.awt.Color(102, 0, 102));
        inputX.setkBorderRadius(50);
        inputX.setkEndColor(new java.awt.Color(102, 0, 102));
        inputX.setkHoverColor(new java.awt.Color(127, 0, 127));
        inputX.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        inputX.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        inputX.setkPressedColor(new java.awt.Color(153, 0, 153));
        inputX.setkSelectedColor(new java.awt.Color(102, 0, 102));
        inputX.setkStartColor(new java.awt.Color(102, 204, 255));
        inputX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputXMousePressed(evt);
            }
        });
        inputX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputXActionPerformed(evt);
            }
        });

        CerrarBoton.setForeground(new java.awt.Color(0, 0, 0));
        CerrarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_power_off_button_32.png"))); // NOI18N
        CerrarBoton.setText("Cerrar");
        CerrarBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CerrarBoton.setkAllowGradient(false);
        CerrarBoton.setkBackGroundColor(new java.awt.Color(153, 0, 153));
        CerrarBoton.setkBorderRadius(50);
        CerrarBoton.setkEndColor(new java.awt.Color(153, 0, 153));
        CerrarBoton.setkForeGround(new java.awt.Color(0, 0, 0));
        CerrarBoton.setkHoverColor(new java.awt.Color(255, 102, 102));
        CerrarBoton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        CerrarBoton.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        CerrarBoton.setkPressedColor(new java.awt.Color(255, 51, 102));
        CerrarBoton.setkSelectedColor(new java.awt.Color(255, 102, 102));
        CerrarBoton.setkStartColor(new java.awt.Color(255, 153, 153));
        CerrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarBotonMousePressed(evt);
            }
        });
        CerrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarBotonActionPerformed(evt);
            }
        });

        inputRestr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_numbers_input_form_32.png"))); // NOI18N
        inputRestr.setText("No. Restricciones");
        inputRestr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputRestr.setkAllowGradient(false);
        inputRestr.setkBackGroundColor(new java.awt.Color(102, 0, 102));
        inputRestr.setkBorderRadius(50);
        inputRestr.setkEndColor(new java.awt.Color(153, 0, 153));
        inputRestr.setkHoverColor(new java.awt.Color(127, 0, 127));
        inputRestr.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        inputRestr.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        inputRestr.setkPressedColor(new java.awt.Color(153, 0, 153));
        inputRestr.setkSelectedColor(new java.awt.Color(102, 0, 102));
        inputRestr.setkStartColor(new java.awt.Color(102, 204, 255));
        inputRestr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputRestrMousePressed(evt);
            }
        });
        inputRestr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRestrActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 2, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Simplex");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_calculator_64.png"))); // NOI18N

        inputY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_add_32.png"))); // NOI18N
        inputY.setText("Ingresar Valor Y");
        inputY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputY.setkAllowGradient(false);
        inputY.setkBackGroundColor(new java.awt.Color(102, 0, 102));
        inputY.setkBorderRadius(50);
        inputY.setkEndColor(new java.awt.Color(153, 0, 153));
        inputY.setkHoverColor(new java.awt.Color(127, 0, 127));
        inputY.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        inputY.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        inputY.setkPressedColor(new java.awt.Color(153, 0, 153));
        inputY.setkSelectedColor(new java.awt.Color(102, 0, 102));
        inputY.setkStartColor(new java.awt.Color(102, 204, 255));
        inputY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputYMousePressed(evt);
            }
        });
        inputY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel9)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CerrarBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputRestr, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(inputY, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(inputX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(inputRestr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 720));

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(50);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 153, 255));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Valor Z");

        ValorZPanel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ValorZPanel.setForeground(new java.awt.Color(255, 255, 255));
        ValorZPanel.setText("45.3");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(ValorZPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorZPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        kGradientPanel2.setkBorderRadius(50);
        kGradientPanel2.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel2.setkGradientFocus(700);
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Valor X");

        ValorXPanel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ValorXPanel.setForeground(new java.awt.Color(255, 255, 255));
        ValorXPanel.setText("3.3");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(ValorXPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValorXPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        kGradientPanel3.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkBorderRadius(50);
        kGradientPanel3.setkEndColor(new java.awt.Color(204, 102, 255));
        kGradientPanel3.setkGradientFocus(700);
        kGradientPanel3.setkStartColor(new java.awt.Color(204, 102, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Valor Y");

        ValorYPanel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ValorYPanel.setForeground(new java.awt.Color(255, 255, 255));
        ValorYPanel.setText("103.3");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(ValorYPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValorYPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_maintenance_32.png"))); // NOI18N
        jLabel7.setText("Restricciones =");

        noResText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        noResText.setText("4");

        tablaRestricciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablaRestricciones.setForeground(new java.awt.Color(0, 0, 0));
        tablaRestricciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Valor X", "Valor Y", "<= Restriccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaRestricciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaRestricciones.setFocusable(false);
        tablaRestricciones.setInheritsPopupMenu(true);
        tablaRestricciones.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablaRestricciones.setName("Tabla Restricciones"); // NOI18N
        tablaRestricciones.setOpaque(false);
        tablaRestricciones.setRowHeight(35);
        tablaRestricciones.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tablaRestricciones.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablaRestricciones.setShowHorizontalLines(false);
        tablaRestricciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaRestricciones);
        tablaRestricciones.getAccessibleContext().setAccessibleName("tablaRest");
        tablaRestricciones.getTableHeader().setFont(new Font("Tahoma",Font.BOLD, 18));

        CalcularBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandix/icons/icons8_calculator_32.png"))); // NOI18N
        CalcularBoton.setText("Calcular");
        CalcularBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CalcularBoton.setIconTextGap(6);
        CalcularBoton.setkAllowGradient(false);
        CalcularBoton.setkBackGroundColor(new java.awt.Color(102, 0, 102));
        CalcularBoton.setkBorderRadius(50);
        CalcularBoton.setkEndColor(new java.awt.Color(102, 0, 102));
        CalcularBoton.setkForeGround(new java.awt.Color(0, 0, 0));
        CalcularBoton.setkHoverColor(new java.awt.Color(127, 0, 127));
        CalcularBoton.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        CalcularBoton.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        CalcularBoton.setkPressedColor(new java.awt.Color(153, 0, 153));
        CalcularBoton.setkSelectedColor(new java.awt.Color(102, 0, 102));
        CalcularBoton.setkStartColor(new java.awt.Color(255, 153, 153));
        CalcularBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CalcularBotonMousePressed(evt);
            }
        });
        CalcularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noResText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalcularBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalcularBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noResText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1010, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputXActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputXActionPerformed

    private void CerrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarBotonActionPerformed

    private void inputRestrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRestrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRestrActionPerformed

    private void CerrarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarBotonMousePressed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_CerrarBotonMousePressed

    private void inputYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputYActionPerformed

    private void CalcularBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularBotonMousePressed
        // TODO add your handling code here:
        int rest = this.cantRestr, 
            incognitas = this.cantRestr + 2;
        int rowSize = this.cantRestr+3;
        //Crear objeto
        Simplex simplex = new Simplex(rest, incognitas);
        //Crear tabla
        float[][] arrTabla = new float[rest + 1][rowSize];
        
        System.out.println(rest+1 +  " -> " + rowSize);
        
        for(int i = 0; i < this.cantRestr; i++){ // recorrer filas 
            for(int j= 0; j < rowSize; j++){ // recorrer columnas
                if(j == i+2){
                    arrTabla[i][j] = 1;
                }
                else if(j >= 2 && j <rowSize-1){
                    arrTabla[i][j] = 0;
                }else if(j<2){
                    arrTabla[i][j] = (float)this.tablaRestricciones.getValueAt(i, j);//Si son los coeficientes de x y
                }else if(j == rowSize-1){
                    arrTabla[i][j] = (float)this.tablaRestricciones.getValueAt(i, 2);// Si llego al final de la tabla
                }
            }
        }
        
        arrTabla[this.cantRestr][0] = (float)this.valorInputX;
        arrTabla[this.cantRestr][1] = (float) this.valorInputY;
        for(int k = 2; k < rowSize; k++){
            arrTabla[this.cantRestr][k] = 0;
        }
        
        for(float[] row: arrTabla){
            for(float x: row){
                System.out.print(x+", ");
            }
            System.out.println();
        }
        simplex.llenaTabla(arrTabla);
    }//GEN-LAST:event_CalcularBotonMousePressed

    private void CalcularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularBotonActionPerformed

    private void inputXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputXMousePressed
        // TODO add your handling code here:
        String inputValue = JOptionPane.showInputDialog("Dame un valor de X");
        while(inputValue == null || inputValue.isEmpty() || inputValue.matches("[A-Za-z]*")){
            inputValue = JOptionPane.showInputDialog("Dame un valor de X valido");
        }
        inputValue = inputValue.trim();
        this.valorInputX = -Float.parseFloat(inputValue);
        this.inputX.setText("Valor actual de X = " + valorInputX);
    }//GEN-LAST:event_inputXMousePressed

    private void inputYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputYMousePressed
        // TODO add your handling code here:
        String inputValue = JOptionPane.showInputDialog("Dame un valor de Y");
        while(inputValue == null || inputValue.isEmpty() || inputValue.matches("[A-Za-z]*")){
            inputValue = JOptionPane.showInputDialog("Dame un valor de Y valido");
        }
        inputValue = inputValue.trim();
        this.valorInputY = -Float.parseFloat(inputValue);
        this.inputY.setText("Valor actual de Y = " + valorInputY);
    }//GEN-LAST:event_inputYMousePressed
    
    private void inputRestrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputRestrMousePressed
        // TODO add your handling code here:
        String inputValue = JOptionPane.showInputDialog("Dame una cantidad de restricciones");
        while(inputValue == null || inputValue.isEmpty() || inputValue.matches("[A-Za-z]*")){
            inputValue = JOptionPane.showInputDialog("Dame una cantidad de restricciones valida");
        }
        inputValue = inputValue.trim();
        this.noResText.setText(inputValue);
        this.cantRestr = Integer.parseInt(inputValue);
    }//GEN-LAST:event_inputRestrMousePressed

    public int getCantidadRestricciones(){
        return this.cantRestr;
    }
    
    public void setValorFinalZ(float valorFinalZ){
        this.valorFinalZ = valorFinalZ;
    }
    
    public void setValorFinalX(float valorFinalX){
        this.valorFinalX = valorFinalX;
    }
        
    public void setValorFinalY(float valorFinalY){
        this.valorFinalY = valorFinalY;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimplexUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimplexUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimplexUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimplexUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimplexUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton CalcularBoton;
    private keeptoo.KButton CerrarBoton;
    private javax.swing.JLabel ValorXPanel;
    private javax.swing.JLabel ValorYPanel;
    private javax.swing.JLabel ValorZPanel;
    private keeptoo.KButton inputRestr;
    private keeptoo.KButton inputX;
    private keeptoo.KButton inputY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel noResText;
    private javax.swing.JTable tablaRestricciones;
    // End of variables declaration//GEN-END:variables
}
